---
title: "Seawater Chemistry"
author: "Samuel Gurr"
date: "8/7/2024"
output: html_document
---

### SET UP
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
# SET WORKING DIRECTORY 
# knitr::opts_knit$set(root.dir = "C:/Users/katherine.mcfarland/Documents/GitHub/EAD-ASEB-Airradians_multigen_OA/larvae") # Katie's
knitr::opts_knit$set(root.dir = "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis") # Sam's
#knitr::opts_knit$set(root.dir = "C:/Users/samuel.gurr/Documents/Github_repositories/EAD-ASEB-Airradians_multigen_OA/RAnalysis/") # Sam's work


```





```{r load data}
# install.packages('gcookbook')
# LOAD PACKAGES :::::::::::::::::::::::::::::::::::::::::::::::::::::::
library(dplyr)
library(ggplot2)
library(reshape2)
library(knitr)
library(kableExtra)
library(car)
library(gcookbook)

# LOAD DATA :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

# F1 
F1_chem_larvae     <- read.csv(file="Data/SeawaterChemistry/F1/F1_water_chemistry_raw_larvae.csv", header=TRUE) # load the chem data
F1_chem_spat.adult <- read.csv(file="Data/SeawaterChemistry/F1/F1_water_chemistry_raw.csv", header=TRUE) # load the chem data


# F2
F2_chem_pre        <- read.csv(file="Data/SeawaterChemistry/F2/F2_water_chemistry_pre_overwinter_raw.csv", header=TRUE) # load the chem data
F2_chem_post       <- read.csv(file="Data/SeawaterChemistry/F2/F2_water_chemistry_post_overwinter_raw.csv", header=TRUE) # load the chem data
# note the pthe pre post is abitrary - GEneveive left off on the cumulative doc at mid January 
# what this readlly representes is wehent DIC broke down, the second as -post; is when the DIC broke down 
# therefore she reports the TA pH TA DC and the DIC pH at the headers of all columns 

```


# MASTER FILE MERGE (rbind) datasets within generation

```{r F1 edit master file}
ncol(F1_chem_larvae) == ncol(F1_chem_spat.adult) # TRUE - same spreadsheet
colnames(F1_chem_larvae) == colnames(F1_chem_spat.adult) # TRUE - also the same

chem.MASTER <- rbind(F1_chem_larvae, F1_chem_spat.adult)

# NOTe: full carbonate chemistry was taken non-continuosly, call all rows that contain full carb

carbchem                <- chem.MASTER[!(is.na(chem.MASTER$War_out_DIC_pH)),] 
carbchem.flagged.DIC.TA <- subset(carbchem, (TCO2_mmol_kgSW > TA_mmol_kgSW)) # 13 rows flagged for DIC<TA
carbchem.flagged.odd    <- subset(carbchem, War_out_DIC_pH > 400) # 8 w/ high aragonite, next highest is 2.05

write.csv((rbind(carbchem.flagged.DIC.TA, carbchem.flagged.odd)), "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/SeawaterChemistry/F1s/flagged_data.csv")

carbchem.MASTER         <- subset(carbchem, !(TCO2_mmol_kgSW > TA_mmol_kgSW)) %>% # DIC>TA omit
  dplyr::filter(War_out_DIC_pH < 3) %>% # omit these odd aragonite points
  dplyr::mutate(pCO2_treatment = 
                  case_when(Treatment == 8 ~ 'Low',
                            Treatment == 7.5 ~ 'Moderate',
                            Treatment == 7 ~ 'Severe'))

write.csv(carbchem.MASTER, "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/SeawaterChemistry/F1s/master/CarbChem_master.csv")

```

## F2 master file 
* total 64 sampling dates over the course of the experiment from spat to adult stage - we dont need all of it though!
```{r F2 edit master file}
F2_chem_pre.OM <- F2_chem_pre %>% dplyr::mutate(Treatment = case_when(Replicate.color %in% 'green/purple' ~ 7.0,
                                          TRUE ~ Treatment)
                                               ) %>% 
                                  tidyr::drop_na(Wca_out)

F2_chem_pre.REP.SUMM <- F2_chem_pre.OM %>% dplyr::select(c(Date, Treatment)) %>% 
                       dplyr::group_by_all() %>% 
                       dplyr::summarise(n=n())

length(unique(F2_chem_pre.REP.SUMM$Date)) # 31 dates when measured over this period! 


View(F2_chem_post.OM)
F2_chem_post.OM <- F2_chem_post %>% 
                                  tidyr::drop_na(Temperature_spec_C)

F2_chem_post.REP.SUMM <- F2_chem_post.OM %>% dplyr::select(c(Date, Treatment)) %>% 
                       dplyr::group_by_all() %>% 
                       dplyr::summarise(n=n())

length(unique(F2_chem_post.REP.SUMM$Date)) # 33 dates when measured over this period! 


```
# PLOTS AND ANALYSIS - Aragonite saturation levels



```{r long master files}


# ALL
# change to long format to properly facet
carbchem.MASTER_long <- carbchem.MASTER %>% 
                          dplyr::select(!c(Treatment)) %>% 
                          dplyr::filter(!(pCO2_treatment %in% 'Severe'),!(Type %in% 'Larvae') ) %>% 
                          dplyr::filter(Replicate %in% c('A','B','C','D','E','F','G','H')) %>% 
                          melt(id.vars=c('Date', 'Replicate', 'Type', 'pCO2_treatment')) %>% 
                          na.omit() %>% 
                          dplyr::mutate(Date = 
                                          as.POSIXct(Date, format = "%m/%d/%Y"),
                                        Month = months(Date),
                                        Year  = year(Date)) 

carbchem.MASTER_long$value <- as.numeric(carbchem.MASTER_long$value) # make numeric

# MEANS PER SAMPLING DAY (reducing replicates within treatment to one mean) 
# aquire means by group for mean SE plotting by Date and treamtent
carbchem.MEANS.by.day <- carbchem.MASTER_long %>% # calc means and standard error
                           dplyr::group_by(Date, Type, pCO2_treatment, variable) %>% 
                           dplyr::summarise(mean = mean(value),
                                            sd   = sd(value),
                                            se   = sd/(sqrt(n())) )

# MONTHLY MEANS (taking the daily means within above and reduce to monthly) 
carbchem.MEANS.monthy.by.rep <-  carbchem.MASTER_long %>% # calc means and standard error
                                   dplyr::group_by(Month, Year, Replicate, pCO2_treatment, variable) %>% 
                                   dplyr::summarise(
                                            mean.month.rep = mean(value),
                                            sd.month.rep   = sd(value),
                                            se.month.rep   = sd.month.rep/(sqrt(n())) ) %>% 
                                   dplyr::mutate(
                                     Month = as.integer(factor(Month, levels = month.name)),
                                     Month_Year = (paste0(Month,'/',Year)),
                                     Date = lubridate::my(Month_Year))
 
carbchem.MEANS.monthy       <- carbchem.MEANS.monthy.by.rep %>% 
                                   dplyr::group_by(Date, Month_Year, pCO2_treatment, variable) %>% 
                                   dplyr::summarise(
                                            mean.month.all = mean(mean.month.rep),
                                            sd.month.all   = sd(mean.month.rep),
                                            se.month.all   = sd.month.all/(sqrt(n())) )


```



```{r plot}


# plot em!
colnames(carbchem.MASTER) # target select

pd <- position_dodge(0.1) # adjust the jitter for the different treatments   


Larvae <- carbchem.MASTER_MEANS %>% 
  dplyr::filter(Type %in% 'Larvae') %>% 
  dplyr::filter(variable %in% (c('Temperature_bucket_C',
                                 'Salinity',
                                 'DO_mg_l',
                                 'pH',
                                 'pH_out',
                                 'TCO2_mmol_kgSW',
                                 'TA_mmol_kgSW',
                                 'War_out_DIC_pH',
                                 'Wca_out'))) %>% 
  ggplot(aes(x=Date, y=mean, shape=Type, colour=factor(pCO2_treatment))) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), colour="black", width=.1, position=pd) +
  geom_line(position=pd) +
  scale_colour_manual(values = c("Low" = "forestgreen",
                                 "Moderate"="orange")) +
                                 # "Severe" = "purple")) +
  theme_classic() +
  geom_point(position=pd, size=2) +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size = 5)) +
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 300000)) +
  facet_wrap(~variable, scales = "free")



pdf("C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/SeawaterChemistry/F1s/plots/F1_larvae.pdf", width=12, height=8)
print(Larvae)
graphics.off()



Juvenile <- carbchem.MASTER_MEANS %>% 
  dplyr::filter(Type %in% 'Juveniles') %>% 
  dplyr::filter(variable %in% (c('Temperature_bucket_C',
                                 'Salinity',
                                 'DO_mg_l',
                                 'pH',
                                 'pH_out',
                                 'TCO2_mmol_kgSW',
                                 'TA_mmol_kgSW',
                                 'War_out_DIC_pH',
                                 'Wca_out'))) %>% 
  ggplot(aes(x=Date, y=mean, shape=Type, colour=factor(pCO2_treatment))) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), colour="black", width=.1, position=pd) +
  geom_line(position=pd) +
  scale_colour_manual(values = c("Low" = "forestgreen",
                                 "Moderate"="orange")) +
                                 # "Severe" = "purple")) +
  theme_classic() +
  geom_point(position=pd, size=2) +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size = 5)) +
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 300000)) +
  facet_wrap(~variable, scales = "free")
print(Juvenile)

pdf("C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/SeawaterChemistry/F1s/plots/F1_juveniles.pdf", width=12, height=8)
print(Juvenile)
graphics.off()


Adult <- carbchem.MASTER_MEANS %>% 
  dplyr::filter(Type %in% 'Adults') %>% 
  dplyr::filter(pCO2_treatment %in% c("Low", "Moderate")) %>% 
  dplyr::filter(variable %in% (c('Temperature_bucket_C',
                                 'Salinity',
                                 'DO_mg_l',
                                 'pH',
                                 'pH_out',
                                 'TCO2_mmol_kgSW',
                                 'TA_mmol_kgSW',
                                 'War_out_DIC_pH',
                                 'Wca_out'))) %>% 
  ggplot(aes(x=Date, y=mean, shape=Type, colour=factor(pCO2_treatment))) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), colour="black", width=.1, position=pd) +
  geom_line(position=pd) +
  scale_colour_manual(values = c("Low" = "forestgreen",
                                 "Moderate"="orange")) +
  theme_classic() +
  geom_point(position=pd, size=2) +
  theme(axis.text.x = element_text(angle = 45, hjust=1, size = 5)) +
  scale_x_date(date_labels="%b-%d",date_breaks  ="3 month")+
  #scale_y_continuous(expand = c(0, 0), limits = c(0, 300000)) +
  facet_wrap(~variable, scales = "free")
print(Adult)

pdf("C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/SeawaterChemistry/F1s/plots/F1_adults.pdf", width=12, height=8)
print(Adult)
graphics.off()




Ph_out_all <- as.data.frame(
  carbchem.MEANS.monthy %>% 
                na.omit() %>% 
                # dplyr::filter(!Type %in% 'Larvae') %>carbchem.MASTER_MEANS.MONTLY% 
                dplyr::filter(pCO2_treatment %in% c("Low", "Moderate")) %>% 
                dplyr::filter(variable %in% c(
                                               'Temperature_bucket_C',
                                               'Salinity',
                                               # 'DO_mg_l',
                                               # 'pH',
                                               'pH_out',
                                               # 'TCO2_mmol_kgSW',
                                               # 'TA_mmol_kgSW',
                                               'War_out_DIC_pH',
                                               'Wca_out'
                                               ))
                                          )

ggplot(data= Ph_out_all, 
         aes(x=Date, 
             y=mean.month.all)) +
             # shape=Type, 
            # colour=factor(pCO2_treatment)))  +
  # stat_summary(geom = "line", fun.y = mean) +
  # stat_summary(geom = "ribbon", fun.data = mean_cl_normal, alpha = 0.3)
  geom_ribbon(aes(ymin = (mean.month.all - sd.month.all ), 
                  ymax = (mean.month.all + sd.month.all ),
                  fill=factor(pCO2_treatment)), alpha = 0.2) +
  geom_line(aes(y = mean.month.all - sd.month.all,
                colour=factor(pCO2_treatment)), 
            linetype = "solid") +
  geom_line(aes(y = mean.month.all + sd.month.all,
                colour=factor(pCO2_treatment)), 
            linetype = "solid") +
  #geom_line()  +
  scale_fill_manual(values=c("forestgreen", "orange"), name="fill") +
  scale_colour_manual(values = c("Low" = "forestgreen",
                                 "Moderate"="orange")) +
  theme_classic() +
  # geom_errorbar(aes(ymin=mean-se, ymax=mean+se), colour="black", width=.1, position=pd) +
  # geom_line(position=pd) +
  # scale_colour_manual(values = c("Low" = "forestgreen",
  #                                "Moderate"="orange")) +
  # theme_classic() +
  # geom_point(position=pd, size=2) +
  # theme(axis.text.x = element_text(angle = 45, hjust=1, size = 5)) +
  # scale_x_date(date_labels="%b-%d",date_breaks  ="3 month")+
  # #scale_y_continuous(expand = c(0, 0), limits = c(0, 300000)) +
  facet_wrap(~variable, scales = "free")



```


```{r SmoothRibbon function with gam}
# how do we get smooth geom ribbon figures
# in summary run gam and use a fine scale for x axis 
# https://stackoverflow.com/questions/61029929/smoothing-geom-ribbon
# A principled way to achieve what you want is to fit a GAM model to your data using the gam() function in mgcv and then apply the predict() function to that model over a finer grid of values for your predictor variable. The grid can cover the span defined by the range of observed values for your predictor variable.
# load R packages
library(ggplot2)
library(mgcv)


SmoothRibbon <- function(datafilename, col_name) {

data <- as.data.frame(
  # carbchem.MEANS.by.day %>% 
                datafilename %>% 
                na.omit() %>% 
                # dplyr::filter(!Type %in% 'Larvae') %>carbchem.MASTER_MEANS.MONTLY% 
                dplyr::filter(pCO2_treatment %in% c("Low", "Moderate")) %>% 
                dplyr::filter(variable %in% (
                                               # 'Temperature_bucket_C',
                                               # 'Salinity',
                                               # 'DO_mg_l',
                                               # 'pH',
                                               # 'pH_out'
                                               col_name
                                               # 'TCO2_mmol_kgSW'
                                               # 'TA_mmol_kgSW',
                                               # 'pCO2_out_matm'
                                               #'War_out_DIC_pH'
                                               # 'Wca_out'
                                               ))
                                          ) %>% 
                 mutate(Date_asnum = dense_rank(Date))


# calc the num days because the Date_asnumin ascending order dot not 
# represent the elapsed time properly as an x axis
data$NumDays  <- as.numeric(
                            difftime(as.Date(data$Date),
                            as.Date(data$Date[1]),
                            units="days")
                            )

data.low      <- data %>% dplyr::filter(pCO2_treatment %in% 'Low')
data.moderate <- data %>% dplyr::filter(pCO2_treatment %in% 'Moderate')
data.all.ordered  <- rbind(data.low, data.moderate)


# fit GAM model
m.low      <- gam(mean ~ s(NumDays), data = data.low) 
m.moderate <- gam(mean ~ s(NumDays), data = data.moderate) 

# define finer grid of predictor values
xnew.low      <- seq(min(data.low$NumDays), 
                     max(data.low$NumDays), by = 0.1) 
xnew.moderate <- seq(min(data.moderate$NumDays), 
                     max(data.moderate$NumDays), by = 0.1) 

# apply predict() function to the fitted GAM model
# using the finer grid of x values
p.low      <- predict(m.low, newdata = data.frame(NumDays = xnew.low), se = TRUE) 
p.moderate <- predict(m.moderate, newdata = data.frame(NumDays = xnew.moderate), se = TRUE) 

# plot the estimated mean values of y (fit) at given x values
# over the finer grid of x values;
# superimpose approximate 95% confidence band for the true 
# mean values of y at given x values in the finer grid
g.low <- data.frame(NumDays = xnew.low, 
            fit = p.low$fit,
            lwr = p.low$fit - 1.96*p.low$se.fit, # 1.96 * SE = 95% CI
            upr = p.low$fit + 1.96*p.low$se.fit  # 1.96 * SE = 95% CI
            ) %>% 
         dplyr::mutate(pCO2_treatment = "Low")

g.moderate <- data.frame(NumDays = xnew.moderate, 
            fit = p.moderate$fit,
            lwr = p.moderate$fit - 1.96*p.moderate$se.fit, 
            upr = p.moderate$fit + 1.96*p.moderate$se.fit) %>% 
         dplyr::mutate(pCO2_treatment = "Moderate")

# r bind the data sets
# use the first date of data and add the elapsed numberic time, not that 1 = seconds, we 
# convert to days by mutliplying by 86400 (seconds in a day)
g.master <- rbind(g.low, g.moderate) %>% 
                  dplyr::mutate(Date = data$Date[1] + NumDays*86400)

theme_set(theme_classic())

p <- ggplot(data = g.master, aes(Date, fit)) + 
  geom_ribbon(aes(ymin = lwr, ymax = upr, fill=factor(pCO2_treatment)), alpha = 0.2) + 
  geom_line(aes(y = lwr,
                colour=factor(pCO2_treatment)),
            linetype = "solid") +
  geom_line(aes(y = upr,
                colour=factor(pCO2_treatment)),
            linetype = "solid") +
  geom_point(data = data.all.ordered, 
             aes(Date, mean,
                 colour=factor(pCO2_treatment)), 
             shape = 3, size =1) +
  ylab(col_name) +
  theme(legend.position="none") +
  scale_fill_manual(values=c("forestgreen", "orange"), name="fill") +
  scale_colour_manual(values=c("forestgreen", "orange"), name="fill") 

print(p)
}


pdf("C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/SeawaterChemistry/F1s/plots/F1_Chem_95CI.pdf", width=8, height=11)
    ggarrange(
          SmoothRibbon(carbchem.MEANS.by.day, "Temperature_bucket_C"),
          SmoothRibbon(carbchem.MEANS.by.day, "Salinity"),
          SmoothRibbon(carbchem.MEANS.by.day, "pCO2_out_matm"),
          SmoothRibbon(carbchem.MEANS.by.day, "pH_out"),
          SmoothRibbon(carbchem.MEANS.by.day, "War_out_DIC_pH"),
          SmoothRibbon(carbchem.MEANS.by.day, "Wca_out"),
          nrow = 3,
          ncol = 2
    )
graphics.off()
```



# TABLE (all data)

```{r use dplyr to build chemistry table, include=FALSE}
carbchem.MASTER_MEANS <- carbchem.MASTER_long %>% # calc means and standard error
   na.omit() %>% 
   dplyr::group_by(Date, Type, pCO2_treatment, variable) %>% 
   dplyr::summarise(mean = mean(value),
                    sd   = sd(value),
                    se   = sd/(sqrt(n())) )

chem_meanDate <- carbchem.MASTER_MEANS %>% 
     na.omit() %>% 
   dplyr::group_by(pCO2_treatment, variable) %>% 
   dplyr::summarise(mean2 = mean(mean),
                    sd   = sd(mean),
                    se   = sd/(sqrt(n())) ,
                    n = n())

carbchem.MASTER_wideMEANS <- dcast(chem_meanDate, pCO2_treatment ~ variable, value.var="mean2")
carbchem.MASTER_wideStErr <- dcast(chem_meanDate, pCO2_treatment ~ variable, value.var="se")
carbchem.MASTER_wideN     <- dcast(chem_meanDate, pCO2_treatment ~ variable, value.var="n")

# final table

colnames(carbchem.MASTER_wideMEANS)
FINAL_TABLE                <- data.frame(matrix(nrow = nrow(carbchem.MASTER_wideMEANS), ncol = 1))

FINAL_TABLE$pCO2_Treatment <- carbchem.MASTER_wideMEANS$pCO2_treatment

FINAL_TABLE$Salinity       <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$Salinity, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$Salinity, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$Salinity,
                                     ")",
                                     sep = "")

FINAL_TABLE$pCO2           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$xCO2_out._dry_at._1_atm_.ppm_.DIC_pH, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$xCO2_out._dry_at._1_atm_.ppm_.DIC_pH, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$xCO2_out._dry_at._1_atm_.ppm_.DIC_pH,
                                     ")",
                                     sep = "")

FINAL_TABLE$Temperature    <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$Temperature_bucket_C, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$Temperature_bucket_C, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$Temperature_bucket_C,
                                     ")",
                                     sep = "")

FINAL_TABLE$pH             <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$pH_out, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$pH_out, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$pH_out,
                                     ")",
                                     sep = "")

FINAL_TABLE$HCO3           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$HCO3_out_mmol_kgSW, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$HCO3_out_mmol_kgSW, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$HCO3_out_mmol_kgSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$CO3           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$CO3_out_mmol_kgSW, digits=3)),
                                             "±",
                                     (signif(carbchem.MASTER_wideStErr$CO3_out_mmol_kgSW, digits=3)), sep="  ")),
                                     " (",
                                     carbchem.MASTER_wideN$CO3_out_mmol_kgSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$TA             <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$TA_mmol_kgSW, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$TA_mmol_kgSW, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$TA_mmol_kgSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$Aragonite.Sat  <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$War_out_DIC_pH, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$War_out_DIC_pH, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$War_out_DIC_pH,
                                     ")",
                                     sep = "")

FINAL_TABLE                <- FINAL_TABLE[,-1] # view table
```


## knitR to print the table 
```{r lable output, echo=TRUE}
FINAL_TABLE %>%
  kbl(caption = "Table 1. Seawater chemistry") %>%
  kable_classic(full_width = T, html_font = "Cambria")
```


#### save data
```{r save tables, echo=TRUE}
# save output table
# write.table(chem_meanDate,"C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis/Output/Water_Chem/Chem.Table_sep.csv",sep=",", row.names=FALSE)  # write table to 
# write.table(FINAL_TABLE,"C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis/Output/Water_Chem/Chem.Table.csv",sep=",", row.names=FALSE)  # write table to 

```










# TABLE (all data)

```{r use dplyr to build chemistry table, include=FALSE}

# change to long format to properly facet
carbchem.MASTER_long <- carbchem.MASTER %>% 
  dplyr::select(!c(Treatment,Replicate)) %>% 
  melt(id.vars=c('Date', 'Type', 'pCO2_treatment'))

carbchem.MASTER_long$value <- as.numeric(carbchem.MASTER_long$value) # make numeric

carbchem.MASTER_MEANS <- carbchem.MASTER_long %>% # calc means and standard error
   na.omit() %>% 
   dplyr::group_by(Date, Type, pCO2_treatment, variable) %>% 
   dplyr::summarise(mean = mean(value),
                    sd   = sd(value),
                    se   = sd/(sqrt(n())) )

chem_meanDate <- carbchem.MASTER_MEANS %>% 
     na.omit() %>% 
   dplyr::group_by(pCO2_treatment, variable) %>% 
   dplyr::summarise(mean2 = mean(mean),
                    sd   = sd(mean),
                    se   = sd/(sqrt(n())) ,
                    n = n())

carbchem.MASTER_wideMEANS <- dcast(chem_meanDate, pCO2_treatment ~ variable, value.var="mean2")
carbchem.MASTER_wideStErr <- dcast(chem_meanDate, pCO2_treatment ~ variable, value.var="se")
carbchem.MASTER_wideN     <- dcast(chem_meanDate, pCO2_treatment ~ variable, value.var="n")

# final table

colnames(carbchem.MASTER_wideMEANS)
FINAL_TABLE                <- data.frame(matrix(nrow = nrow(carbchem.MASTER_wideMEANS), ncol = 1))

FINAL_TABLE$pCO2_Treatment <- carbchem.MASTER_wideMEANS$pCO2_treatment

FINAL_TABLE$Salinity       <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$Salinity, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$Salinity, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$Salinity,
                                     ")",
                                     sep = "")

FINAL_TABLE$pCO2           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$xCO2_out._dry_at._1_atm_.ppm_.DIC_pH, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$xCO2_out._dry_at._1_atm_.ppm_.DIC_pH, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$xCO2_out._dry_at._1_atm_.ppm_.DIC_pH,
                                     ")",
                                     sep = "")

FINAL_TABLE$Temperature    <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$Temperature_bucket_C, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$Temperature_bucket_C, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$Temperature_bucket_C,
                                     ")",
                                     sep = "")

FINAL_TABLE$pH             <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$pH_out, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$pH_out, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$pH_out,
                                     ")",
                                     sep = "")

FINAL_TABLE$HCO3           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$HCO3_out_mmol_kgSW, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$HCO3_out_mmol_kgSW, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$HCO3_out_mmol_kgSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$CO3           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$CO3_out_mmol_kgSW, digits=3)),
                                             "±",
                                     (signif(carbchem.MASTER_wideStErr$CO3_out_mmol_kgSW, digits=3)), sep="  ")),
                                     " (",
                                     carbchem.MASTER_wideN$CO3_out_mmol_kgSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$TA             <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$TA_mmol_kgSW, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$TA_mmol_kgSW, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$TA_mmol_kgSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$Aragonite.Sat  <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$War_out_DIC_pH, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$War_out_DIC_pH, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$War_out_DIC_pH,
                                     ")",
                                     sep = "")

FINAL_TABLE                <- FINAL_TABLE[,-1] # view table
```


## knitR to print the table 
```{r lable output, echo=TRUE}
FINAL_TABLE %>%
  kbl(caption = "Table 1. Seawater chemistry") %>%
  kable_classic(full_width = T, html_font = "Cambria")
```


#### save data (food x OA manuscript)
```{r save tables, echo=TRUE}
# save output table
# write.table(chem_meanDate,"C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis/Output/Water_Chem/Chem.Table_sep.csv",sep=",", row.names=FALSE)  # write table to 
# write.table(FINAL_TABLE,"C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis/Output/Water_Chem/Chem.Table.csv",sep=",", row.names=FALSE)  # write table to 

```
