---
title: "F1_Lengths_analysis"
author: "Samuel Gurr"
date: "2024-01-05"
output: html_document
---

# Objectives: 

* (i) view the mean, variation, and number of samples

* (ii) plot the data 

* (iii) run stats

### set up load libraries and set working dir for the script 
```{r setup, include= FALSE, echo = FALSE}

# LOAD PACKAGES :::::::::::::::::::::::::::::::::::::::::::::::::::::::
library(dplyr)
library(ggplot2)
library(forcats)
library(lme4)
# library(lmerTest)
# library(performance)
# install.packages('')
library(car)
library(ggpubr)
# library(SciViews)
library(Rmisc)
# library(hrbrthemes)lmerTest

# SET WORKING DIRECTORY :::::::::::::::::::::::::::::::::::::::::::::::
knitr::opts_knit$set(root.dir = "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis")

```

## Load data 

```{r, load data}

# F2s
F1_length <- read.csv(file="Data/Physiology/Length/F1/cumulative_raw/F1_lengths_raw.csv",
                          header=T,stringsAsFactors=FALSE, fileEncoding="latin1") 

# unique dates for the dry weight data 
unique(F1_length$Date)
# View(F1_dryweights)

F1_length_master <- F1_length %>% # master data file
                    dplyr::mutate(pCO2 = as.factor(case_when(Treatment == "Low OA" ~ "500 μatm", # add column for pCO2
                                                   Treatment == "Moderate OA" ~ "800 μatm",
                                                   Treatment == "High OA" ~ "1200 μatm"))) %>% 
                    dplyr::mutate(pCO2 = fct_relevel(pCO2, c("500 μatm","800 μatm","1200 μatm")))# relevel for plotting!

```

# (i) summary of data 

* by date pcO2 and tank replicate (for mean Se plots - related to statistics!)


```{r dry weights, echo = FALSE}
F1_length_master$Length_mm <- as.numeric(F1_length_master$Length_mm)

# means by date and pCO2 - not by replicate tank!
F1_length_master %>%  
       summarySE(measurevar="Length_mm", groupvars=c("Age_DPF","pCO2")) %>% 
       dplyr::arrange(Length_mm)

F1_length_MEANS_bytank <-  F1_length_master %>%  
                            summarySE(measurevar="Length_mm", groupvars=c("Date","Age_DPF","pCO2","Replicate")) 

write.csv(F1_length_MEANS_bytank, "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Length/F1/F1_Mean_Length_by_tank.csv")
```


# (ii) plot data 

### Shell length data

* raw data 

```{r Figures - shell length}

# histogram 

F1_Length_Histograms_EARLY <- F1_length_master %>%
                          dplyr::filter(Age_DPF < 30) %>% 
                          # dplyr::filter(!pCO2 %in% "1200 μatm") %>% 
                          ggplot( aes(x=Length_mm, fill=pCO2)) +
                            geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
                            scale_fill_manual(values=c("forestgreen","darkorange2", "purple")) +
                            theme_classic() +
                            # theme_ipsum() +
                            labs(fill="") + 
                            labs(fill='pCO2 treatment') +
                            scale_x_continuous(name ="Shell length (mm)")+
                            facet_wrap(~Age_DPF, scales = "free_y")


F1_Length_Histograms <- F1_length_master %>%
                          dplyr::filter(Age_DPF >= 30) %>% 
                          dplyr::filter(!pCO2 %in% "1200 μatm") %>% 
                          ggplot( aes(x=Length_mm, fill=pCO2)) +
                            geom_histogram( alpha=0.6, position = 'identity') +
                            scale_fill_manual(values=c("forestgreen","darkorange2")) +
                            theme_classic() +
                            # theme_ipsum() +
                            # labs(fill="") + 
                            labs(fill='pCO2 treatment') +
                            scale_x_continuous(name ="Shell length (mm)")+
                            facet_wrap(~Age_DPF, scales = "free_y")
  
# Mean SE by tank 

F1_length_MEANS <-  F1_length_MEANS_bytank %>%  
                            summarySE(measurevar="Length_mm", groupvars=c("Age_DPF","pCO2")) %>% 
                            dplyr::arrange(Length_mm) 

F1_Length_MeanSE <- F1_length_MEANS %>%
                          dplyr::filter(Age_DPF >= 30) %>% 
                          dplyr::filter(!pCO2 %in% "1200 μatm") %>% 
                          ggplot(aes(x=(Age_DPF), 
                                     y=Length_mm, 
                                     color=as.factor(pCO2))) +
                          geom_point(position=position_dodge(.5))+ 
                          scale_color_manual(values=c("forestgreen",
                                                      "darkorange2"))+
                          geom_errorbar(aes(ymin=Length_mm-se, 
                                            ymax=Length_mm+se), width=.2,
                                        position=position_dodge(.5))+
                          ggtitle("Shell lengths (mm) - mean+-SE") +
                          theme_classic() +  
                          xlab("Age (dpf)") +
                         #xlab("Age (d)") +
                          theme(panel.grid.major = element_blank(), 
                                panel.grid.minor = element_blank(),
                                legend.position="none")+ 
                          scale_y_continuous(name ="Shell length (mm)")+
                          geom_line(stat = "identity", size=1.0)+
                          # labs(color='pCO2 treatment') + # legend name
                          theme(text = element_text(size=10)) 


# arrange plots 


# pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_OA/RAnalysis/Output/Survival_size/20210930_survival.pdf"))
pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Length/F1/F1_Length_histogram_meanSE.pdf"),width=10, height=5)
ggarrange(F1_Length_Histograms, F1_Length_MeanSE, ncol = 2)
dev.off()


pdf(paste0("C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Length/F1/F1_Length_meanSE.pdf"),width=8, height=4)
print(F1_Length_MeanSE)
dev.off()

```


#  statistics

```{r stats}

# call after 30 days post fertilization and 
F1_length_MEANS_growout <- F1_length_MEANS_bytank %>% 
                              dplyr::filter(Age_DPF >= 30) %>% 
                              dplyr::filter(!pCO2 %in% "1200 μatm")
# NOTE: we only had a handful of pH 7 1200 uatm pCO2 animals for the high treatment - we are not using these 
# for length assessment as they are confounded by low tank density (more access to food) and were not used to yield our F2s! 
# In Summary - run stats for JUST the low and moderate pCO2s 

# (1) First, run anova within date for all records (for looped!)
ANOVA_Age_DPF      <- as.data.frame(unique(F1_length_MEANS_growout$Age_DPF)) # call a list to loop in 

AOVdf_total       <- data.frame() # start dataframe, this will be the master output
DF_loop           <- data.frame(matrix(nrow = 1, ncol = 12)) # create dataframe to save during for loop
colnames(DF_loop) <- c('Age_DPF', 'Metric', 'ShapiroWilk', 'ResidNorm', 'Levenes', 'HomogVar', 'model', 'DF.num' , 'DF.denom', 'F_val','P_val', 'SigDif') # names for comuns in the for loop

for (i in 1:nrow(ANOVA_Age_DPF)) {
  
  Age_loop     <- as.character(ANOVA_Age_DPF[i,])
  data_loop     <- F1_length_MEANS_growout %>% # call the dataset above - after 30 dpf and for only the two treatments 
    dplyr::filter(Age_DPF %in% Age_loop) %>% 
    dplyr::select(Age_DPF, pCO2, Length_mm)

    # high cholorphyll model

    DF_loop$Age_DPF     <- Age_loop
    DF_loop$Metric      <- colnames(data_loop[3])
    
    # run both modles
    AOVmod              <- aov(lm(data_loop$Length_mm ~ as.factor(data_loop$pCO2)))
    KWmod               <- kruskal.test(data_loop$Length_mm  ~ as.factor(data_loop$pCO2))
    
    # normality tests for the anova model - asign 
    DF_loop$ShapiroWilk <- shapiro.test(resid(AOVmod))[[2]]
    DF_loop$ResidNorm   <- if( shapiro.test(resid(AOVmod))[[2]] > 0.05) {
      'YES'} else {'NO'}
    DF_loop$Levenes     <- leveneTest(AOVmod)[[3]][[1]]
    DF_loop$HomogVar    <- if( leveneTest(AOVmod)[[3]][[1]] > 0.05) {
      'YES'} else {'NO'}
    
    if(shapiro.test(resid(AOVmod))[[2]] > 0.05 & leveneTest(AOVmod)[[3]][[1]] > 0.05) {
        DF_loop$model       <- 'one-way AOV; x ~ treatment'
        DF_loop$DF.num      <- summary(AOVmod)[[1]][["Df"]][1]
        DF_loop$DF.denom    <- summary(AOVmod)[[1]][["Df"]][2]
        DF_loop$F_val       <- summary(AOVmod)[[1]][["F value"]][1]
        DF_loop$P_val       <- summary(AOVmod)[[1]][["Pr(>F)"]][1]
        DF_loop$SigDif      <- if( (summary(AOVmod)[[1]][["Pr(>F)"]][1]) > 0.05) {
          'NO'} else {'YES'}

      } else {
        DF_loop$model       <- 'kruskal-wallis; x ~ treatment'
        DF_loop$DF.num      <- (KWmod)[[2]][["df"]][1]
        DF_loop$DF.denom    <- NA
        DF_loop$F_val       <- NA
        DF_loop$P_val       <- (KWmod)[[3]]
        DF_loop$SigDif      <- if( ((KWmod)[[3]]) > 0.05) {
          'NO'} else {'YES'}
      }
    
    # asign loop and cumulative output table
    df          <- data.frame(DF_loop) # name dataframe for this single row
    AOVdf_total <- rbind(AOVdf_total,DF_loop) #bind to a cumulative list dataframe
    print(AOVdf_total) # print to monitor progress
}
View(AOVdf_total) # view all the anova tests within data 
View(AOVdf_total %>% dplyr::filter(P_val < 0.05)) # 243, 275, 318 are significnatly different via one0-way anova

write.csv(AOVdf_total, "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Length/F1/F1_Length_ANOVA_table.csv")


# (2)  You can easitly do #1 by piping in the formula here BUT this does not have contingency based on assumptions
F1_length_MEANS_growout %>%
  group_by(Age_DPF) %>%
  t_test(data =., Length_mm ~ pCO2) %>% #243, 275, 318 are significnatly different via one0-way anova
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj") # with bonferroni JUST 273 is significantly different!


# (3) GLMM 
F1_length_MEANS_growout$ID <- paste0(F1_length_MEANS_growout$Replicate,
                                     '_',
                                     F1_length_MEANS_growout$pH) # ID variable to run the GLMM withput averaging!

F1_GLMM <- glmer(
                   Length_mm ~ 
                    pCO2 * Age_DPF + (1 | ID), 
                      data = F1_length_MEANS_growout, 
                     # gaussian(link = "identity")
                     Gamma(link="identity") 
                     # Gamma(link="log") 
                  )

summary(F1_GLMM)

# check the distribution of residuals 
simulationOutput <- simulateResiduals(fittedModel = F1_GLMM, use.u = T)
residuals        <- residuals(F1_GLMM, type = "response", retype="normalized")

# pdf(file="Output/1_Survival_Growth/size_growth/Experiment4/Experiment4_Length_GLMM_QQ_Resid.pdf", height = 4, width = 7)
plot(simulationOutput)
# dev.off()

# pdf(file="Output/1_Survival_Growth/size_growth/Experiment4/Experiment4_Length_GLMM_Resid.pdf", height = 5, width = 5)
plot(residuals)
# dev.off()

# output the anova table 
car::Anova(F1_GLMM, type=3) # JUST AN EFFECT OF TIME
```