---
title: "F1_RespirationRates_analysis"
author: "Samuel Gurr"
date: "2024-01-08"
output:
  pdf_document:
    latex_engine: xelatex
---


```{r setup, include= FALSE, echo = FALSE}

# LOAD PACKAGES :::::::::::::::::::::::::::::::::::::::::::::::::::::::
library(dplyr)
library(ggplot2)
library(forcats)
library(lme4)
library(lmerTest)
library(performance)
library(car)
library(kableExtra)
library(pander)
library(data.table)
library(Rmisc)
library(devtools)
library(ggpubr)
library(SciViews)
library(lubridate)

# SET WORKING DIRECTORY :::::::::::::::::::::::::::::::::::::::::::::::
knitr::opts_knit$set(root.dir = "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis")

```


```{r, load data}
# LOAD DATA :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
RR_formatted_F1s <- read.csv(file="Output/Respiration/F1/F1_RR_calc_master.csv") %>% dplyr::select(-X)


# formatted for plotting and stats 
# length b factor norm
F1_RR_Length_Meanbytank <- RR_formatted_F1s%>% 
                            summarySE(measurevar="resp_umol_hr_bFactorNormLength.MEAN", 
                                      groupvars=c("Date", "Age", "pCO2", "Chamber_tank"))
unique(F1_RR_Length_Meanbytank$Date) # "10/26/2021" "10/26/2022" "2/2/2022"   "3/1/2022"   "9/14/2021"  "9/22/2022"  "9/30/2021"

write.csv(F1_RR_Length_Meanbytank, "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_Mean_RRLength_by_tank.csv")

# length b factor norm
F1_RR_TDW_Meanbytank <- RR_formatted_F1s%>% 
                            summarySE(measurevar="resp_umol_hr_bFactorNormTDW.MEAN", 
                                      groupvars=c("Date", "Age", "pCO2", "Chamber_tank")) %>% 
                            filter(!is.na(resp_umol_hr_bFactorNormTDW.MEAN))
unique(F1_RR_TDW_Meanbytank$Date)  # "10/26/2021" "10/26/2022" "2/2/2022"   "3/1/2022"   "9/22/2022"                         

write.csv(F1_RR_TDW_Meanbytank, "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_Mean_RRTDW_by_tank.csv")


```


# SHELL LENGTH (allometric scalingexpnent applied - review "RespirationRates_calc_bfactor.Rmd")

## plots
```{r, by MM LENGTH,echo = FALSE, results='hide',message = FALSE, warning = FALSE}

 
# LENGTH  ---------------------------------------------------------------------------- #

F1s.BOXPLOT_Length_bfactor.MEAN <- RR_formatted_F1s %>% 
                                      ggplot(aes(x = factor(Age), 
                                                 y = resp_umol_hr_bFactorNormLength.MEAN, 
                                                 fill = pCO2)) +
                                             geom_boxplot(alpha = 0.5, # color hue
                                                 width=0.6, # boxplot width
                                                 outlier.size=0, # make outliers small
                                                 position = position_dodge(preserve = "single")) + 
                                             geom_point(pch = 19, 
                                                        position = position_jitterdodge(0.01), 
                                                        size=1) +
                                             scale_fill_manual(values=c("forestgreen","darkorange2")) +
                                             theme_classic() + 
                                             ggtitle("RR b factor corrected (all data points)") +
                                             theme(legend.position="none",
                                                   axis.title.y=element_text(size=7),
                                                   axis.title.x=element_text(size=7),
                                                   axis.text.x=element_text(size=7)) +
                                             ylab("RR") +
                                             scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                                             stat_summary(fun.y=mean, 
                                                          geom = "errorbar", 
                                                          aes(ymax = ..y.., ymin = ..y..), 
                                                          width = 0.6, 
                                                          size=0.4, 
                                                          linetype = "dashed", 
                                                          position = position_dodge(preserve = "single")) 

# convert meand by tank to summrizing means by treatment and age 
F1_RR_Length_Means <- F1_RR_Length_Meanbytank %>% 
                            summarySE(measurevar="resp_umol_hr_bFactorNormLength.MEAN", 
                                      groupvars=c("Age", "pCO2"))


F1_RR_Length_MeanSE <-  F1_RR_Length_Means %>%
                                 ggplot(aes(x=(as.factor(Age)), 
                                               y=resp_umol_hr_bFactorNormLength.MEAN, 
                                               color=as.factor(pCO2))) +
                                    geom_point(position=position_dodge(.5))+ 
                                    scale_color_manual(values=c("forestgreen",
                                                                "darkorange2"))+
                                    geom_errorbar(aes(ymin=resp_umol_hr_bFactorNormLength.MEAN-se, 
                                                      ymax=resp_umol_hr_bFactorNormLength.MEAN+se), width=.2,
                                                  position=position_dodge(.5))+
                                    ggtitle("RR b factor corrected (mean+-SE)") +
                                    theme_classic() +  
                                    xlab("Age (dpf)") +
                                    ylab("RR") +
                                   #xlab("Age (d)") +
                                    theme(panel.grid.major = element_blank(), 
                                          panel.grid.minor = element_blank(),
                                          legend.position="none")+ 
                                    scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                                    # labs(color='pCO2 treatment') + # legend name
                                    theme(text = element_text(size=10))

F1_RR_Length_MeanSE_sub <-  F1_RR_Length_Means %>% # matches the timepoints for ER measurements
                                 dplyr::filter(Age > 90) %>% #
                                 ggplot(aes(x=(as.numeric(Age)), 
                                               y=resp_umol_hr_bFactorNormLength.MEAN, 
                                               color=as.factor(pCO2))) +
                                    geom_point(position=position_dodge(.5))+ 
                                    scale_color_manual(values=c("forestgreen",
                                                                "darkorange2"))+
                                    geom_errorbar(aes(ymin=resp_umol_hr_bFactorNormLength.MEAN-se, 
                                                      ymax=resp_umol_hr_bFactorNormLength.MEAN+se), width=.2,
                                                  position=position_dodge(.5))+
                                    ggtitle("RR b factor corrected (mean+-SE)") +
                                    theme_classic() +  
                                    xlab("Age (dpf)") +
                                    ylab("RR") +
                                   #xlab("Age (d)") +
                                    theme(panel.grid.major = element_blank(), 
                                          panel.grid.minor = element_blank(),
                                          legend.position="none")+ 
                                    scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) 
                                    scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                                    # labs(color='pCO2 treatment') + # legend name
                                    theme(text = element_text(size=10))

# save
pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_RR_LENGTH_bfactor.pdf"), width = 6, height = 8)
print(ggarrange(F1s.BOXPLOT_Length_bfactor.MEAN, F1_RR_Length_MeanSE, nrow = 2)) # print the model diagnostics 
dev.off()

pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_RR_LENGTH_bfactor_meanSE.pdf"), width = 8, height = 3)
print(F1_RR_Length_MeanSE) # print the model diagnostics 
dev.off()


pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_RR_LENGTH_bfactor_meanSEsubset.pdf"), width = 8, height = 3)
print(F1_RR_Length_MeanSE_sub) # print the model diagnostics 
dev.off()
```

## statistics
``` {r, standardize & ANOVA stats,echo = FALSE, results='hide',message = FALSE, warning = FALSE}

# (1) First, run anova within date for all records (for looped!)
ANOVA_Dates       <- as.data.frame(unique(F1_RR_Length_Meanbytank$Date)) # call a list to loop in 
AOVdf_total       <- data.frame() # start dataframe, this will be the master output
DF_loop           <- data.frame(matrix(nrow = 1, ncol = 13)) # create dataframe to save during for loop
colnames(DF_loop) <- c('Date', 'Age', 'Metric', 'model', 'ShapiroWilk', 'ResidNorm', 'Levenes', 'HomogVar', 'DF.num' , 'DF.denom', 'F_val','P_val', 'SigDif') # names for comuns in the for loop

for (i in 1:nrow(ANOVA_Dates)) {

  date_loop     <- as.character(ANOVA_Dates[i,])
  data_loop     <- F1_RR_Length_Meanbytank %>% 
                          dplyr::filter(Date == date_loop) %>% 
                          dplyr::select(Date, Age, pCO2, resp_umol_hr_bFactorNormLength.MEAN) %>% 
                          na.omit()

        AOVmod              <- aov(lm(data_loop$resp_umol_hr_bFactorNormLength.MEAN ~ data_loop$pCO2))
        DF_loop$Date        <- date_loop
        DF_loop$Age         <- data_loop$Age[1]
        DF_loop$Metric      <- 'RR; LENGTH b factor normalized'
        
        # run both modles
        AOVmod              <- aov(lm(data_loop$resp_umol_hr_bFactorNormLength.MEAN ~ as.factor(data_loop$pCO2)))
        KWmod               <- kruskal.test(data_loop$resp_umol_hr_bFactorNormLength.MEAN  ~ as.factor(data_loop$pCO2))
        
        # normality tests for the anova model - asign 
        DF_loop$ShapiroWilk <- shapiro.test(resid(AOVmod))[[2]]
        DF_loop$ResidNorm   <- if( shapiro.test(resid(AOVmod))[[2]] > 0.05) {
          'YES'} else {'NO'}
        DF_loop$Levenes     <- leveneTest(AOVmod)[[3]][[1]]
        DF_loop$HomogVar    <- if( leveneTest(AOVmod)[[3]][[1]] > 0.05) {
          'YES'} else {'NO'}
        
        if(shapiro.test(resid(AOVmod))[[2]] > 0.05 & leveneTest(AOVmod)[[3]][[1]] > 0.05) {
            DF_loop$model       <- 'one-way AOV; x ~ treatment'
            DF_loop$DF.num      <- summary(AOVmod)[[1]][["Df"]][1]
            DF_loop$DF.denom    <- summary(AOVmod)[[1]][["Df"]][2]
            DF_loop$F_val       <- summary(AOVmod)[[1]][["F value"]][1]
            DF_loop$P_val       <- summary(AOVmod)[[1]][["Pr(>F)"]][1]
            DF_loop$SigDif      <- if( (summary(AOVmod)[[1]][["Pr(>F)"]][1]) > 0.05) {
              'NO'} else {'YES'}
    
          } else {
            DF_loop$model       <- 'kruskal-wallis; x ~ treatment'
            DF_loop$DF.num      <- (KWmod)[[2]][["df"]][1]
            DF_loop$DF.denom    <- NA
            DF_loop$F_val       <- NA
            DF_loop$P_val       <- (KWmod)[[3]]
            DF_loop$SigDif      <- if( ((KWmod)[[3]]) > 0.05) {
          'NO'} else {'YES'}
      }
        
        # asign loop and cumulative output table
        df          <- data.frame(DF_loop) # name dataframe for this single row
        AOVdf_total <- rbind(AOVdf_total,DF_loop) #bind to a cumulative list dataframe
        print(AOVdf_total) # print to monitor progress
        
}
# View(AOVdf_total) # view all the anova tests within data 


# WRITE CSV OF THE MASTER FILE
write.csv(AOVdf_total, "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_RR_LENGTH_Statistics.csv")
#write.csv(Biodep_Master, "C:/Users/samuel.gurr/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Biodeposition/Biodeposition_master.csv")
                    


```

## posthc test -  one sig effect on Age 218 (3/1/2022)
```{r posthoc test 218 DPF }
                    
mod218 <- aov(lm(resp_umol_hr_bFactorNormLength.MEAN ~ pCO2,data = (F1_RR_Length_Meanbytank %>% dplyr::filter(Age %in% 218)) ))
summary(mod218)
#             Df Sum Sq Mean Sq F value Pr(>F)  
# pCO2         1  13.77  13.770   6.941 0.0196 *
TukeyHSD(mod218)
#                       diff       lwr      upr     p adj
# 800 uatm-500 uatm 1.855416 0.3449731 3.365859 0.0196082
```



# TDW (allometric scaling expnent applied - review "RespirationRates_calc_bfactor.Rmd")

## plots
```{r, by TDW,echo = FALSE, results='hide',message = FALSE, warning = FALSE}


# LENGTH  ---------------------------------------------------------------------------- #

F1s.BOXPLOT_TDW_bfactor.MEAN <- RR_formatted_F1s %>% 
                                      ggplot(aes(x = factor(Age), 
                                                 y = resp_umol_hr_bFactorNormTDW.MEAN, 
                                                 fill = pCO2)) +
                                             geom_boxplot(alpha = 0.5, # color hue
                                                 width=0.6, # boxplot width
                                                 outlier.size=0, # make outliers small
                                                 position = position_dodge(preserve = "single")) + 
                                             geom_point(pch = 19, 
                                                        position = position_jitterdodge(0.01), 
                                                        size=1) +
                                             scale_fill_manual(values=c("forestgreen","darkorange2")) +
                                             theme_classic() + 
                                             ggtitle("RR b factor corrected (all data points)") +
                                             theme(legend.position="none",
                                                   axis.title.y=element_text(size=7),
                                                   axis.title.x=element_text(size=7),
                                                   axis.text.x=element_text(size=7)) +
                                             ylab("RR") +
                                             scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                                             stat_summary(fun.y=mean, 
                                                          geom = "errorbar", 
                                                          aes(ymax = ..y.., ymin = ..y..), 
                                                          width = 0.6, 
                                                          size=0.4, 
                                                          linetype = "dashed", 
                                                          position = position_dodge(preserve = "single")) 

# convert meand by tank to summrizing means by treatment and age 
F1_RR_TDW_Means <- F1_RR_TDW_Meanbytank %>% 
                            summarySE(measurevar="resp_umol_hr_bFactorNormTDW.MEAN", 
                                      groupvars=c("Age", "pCO2"))


F1_RR_TDW_MeanSE <-  F1_RR_TDW_Means %>%
                                 ggplot(aes(x=(as.factor(Age)), 
                                               y=resp_umol_hr_bFactorNormTDW.MEAN, 
                                               color=as.factor(pCO2))) +
                                    geom_point(position=position_dodge(.5))+ 
                                    scale_color_manual(values=c("forestgreen",
                                                                "darkorange2"))+
                                    geom_errorbar(aes(ymin=resp_umol_hr_bFactorNormTDW.MEAN-se, 
                                                      ymax=resp_umol_hr_bFactorNormTDW.MEAN+se), width=.2,
                                                  position=position_dodge(.5))+
                                    ggtitle("RR b factor corrected (mean+-SE)") +
                                    theme_classic() +  
                                    xlab("Age (dpf)") +
                                    ylab("RR") +
                                   #xlab("Age (d)") +
                                    theme(panel.grid.major = element_blank(), 
                                          panel.grid.minor = element_blank(),
                                          legend.position="none")+ 
                                    scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
                                    # labs(color='pCO2 treatment') + # legend name
                                    theme(text = element_text(size=10))


# save
pdf(paste0(filename = "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_RR_TDW_bfactor.pdf"), width = 6, height = 8)
print(ggarrange(F1s.BOXPLOT_TDW_bfactor.MEAN, F1_RR_TDW_MeanSE, nrow = 2)) # print the model diagnostics 
dev.off()



```

## statistics
``` {r, standardize & ANOVA stats,echo = FALSE, results='hide',message = FALSE, warning = FALSE}

# (1) First, run anova within date for all records (for looped!)
ANOVA_Dates       <- as.data.frame(unique(F1_RR_TDW_Meanbytank$Date)) # call a list to loop in 
AOVdf_total       <- data.frame() # start dataframe, this will be the master output
DF_loop           <- data.frame(matrix(nrow = 1, ncol = 13)) # create dataframe to save during for loop
colnames(DF_loop) <- c('Date', 'Age', 'Metric', 'model', 'ShapiroWilk', 'ResidNorm', 'Levenes', 'HomogVar', 'DF.num' , 'DF.denom', 'F_val','P_val', 'SigDif') # names for comuns in the for loop

for (i in 1:nrow(ANOVA_Dates)) {

  date_loop     <- as.character(ANOVA_Dates[i,])
  data_loop     <- F1_RR_TDW_Meanbytank %>% 
                          dplyr::filter(Date == date_loop) %>% 
                          dplyr::select(Date, Age, pCO2, resp_umol_hr_bFactorNormTDW.MEAN) %>% 
                          na.omit()

        AOVmod              <- aov(lm(data_loop$resp_umol_hr_bFactorNormTDW.MEAN ~ data_loop$pCO2))
        DF_loop$Date        <- date_loop
        DF_loop$Age         <- data_loop$Age[1]
        DF_loop$Metric      <- 'RR; LENGTH b factor normalized'
        
        # run both modles
        AOVmod              <- aov(lm(data_loop$resp_umol_hr_bFactorNormTDW.MEAN ~ as.factor(data_loop$pCO2)))
        KWmod               <- kruskal.test(data_loop$resp_umol_hr_bFactorNormTDW.MEAN  ~ as.factor(data_loop$pCO2))
        
        # normality tests for the anova model - asign 
        DF_loop$ShapiroWilk <- shapiro.test(resid(AOVmod))[[2]]
        DF_loop$ResidNorm   <- if( shapiro.test(resid(AOVmod))[[2]] > 0.05) {
          'YES'} else {'NO'}
        DF_loop$Levenes     <- leveneTest(AOVmod)[[3]][[1]]
        DF_loop$HomogVar    <- if( leveneTest(AOVmod)[[3]][[1]] > 0.05) {
          'YES'} else {'NO'}
        
        if(shapiro.test(resid(AOVmod))[[2]] > 0.05 & leveneTest(AOVmod)[[3]][[1]] > 0.05) {
            DF_loop$model       <- 'one-way AOV; x ~ treatment'
            DF_loop$DF.num      <- summary(AOVmod)[[1]][["Df"]][1]
            DF_loop$DF.denom    <- summary(AOVmod)[[1]][["Df"]][2]
            DF_loop$F_val       <- summary(AOVmod)[[1]][["F value"]][1]
            DF_loop$P_val       <- summary(AOVmod)[[1]][["Pr(>F)"]][1]
            DF_loop$SigDif      <- if( (summary(AOVmod)[[1]][["Pr(>F)"]][1]) > 0.05) {
              'NO'} else {'YES'}
    
          } else {
            DF_loop$model       <- 'kruskal-wallis; x ~ treatment'
            DF_loop$DF.num      <- (KWmod)[[2]][["df"]][1]
            DF_loop$DF.denom    <- NA
            DF_loop$F_val       <- NA
            DF_loop$P_val       <- (KWmod)[[3]]
            DF_loop$SigDif      <- if( ((KWmod)[[3]]) > 0.05) {
          'NO'} else {'YES'}
      }
        
        # asign loop and cumulative output table
        df          <- data.frame(DF_loop) # name dataframe for this single row
        AOVdf_total <- rbind(AOVdf_total,DF_loop) #bind to a cumulative list dataframe
        print(AOVdf_total) # print to monitor progress
        
}
# View(AOVdf_total) # view all the anova tests within data 


# WRITE CSV OF THE MASTER FILE
write.csv(AOVdf_total, "C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Respiration/F1/F1_RR_TDW_Statistics.csv")
#write.csv(Biodep_Master, "C:/Users/samuel.gurr/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis/Output/Biodeposition/Biodeposition_master.csv")
                    


```

## posthc test -  one sig effect on Age 218 (3/1/2022)
```{r posthoc test 218 DPF }
                    
mod218 <- aov(lm(resp_umol_hr_bFactorNormTDW.MEAN ~ pCO2,data = (F1_RR_TDW_Meanbytank %>% dplyr::filter(Age %in% 218)) ))
summary(mod218)
#             Df Sum Sq Mean Sq F value Pr(>F)  
# pCO2         1  97.97   97.97   5.126   0.04 *
# Residuals   14 267.56   19.11
TukeyHSD(mod218)
#                       diff       lwr      upr     p adj
# 800 uatm-500 uatm 4.948947 0.2608079 9.637087 0.0399756
```


